webrecruitment/music/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:person_id>/', views.detailes, name='detailes'),
    path('statistics/', views.statistics, name="statistics" ),
    path('new/', views.new, name="new"),
    path('ajax/', views.ajax, name="ajax"),
]

webrecruitment/webrecruitment/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('music/', include('music.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),     
]

webrecruitment/music/models.py
from django.db import models


class Person(models.Model):
 STATE_CHOICES =(
    ('Gujarat','Gujarat'),
    ('Maharashtra','Maharashtra'),
    ('Karnataka','Karnataka'),
 )
 CITY_CHOICES =(
    ('Bahavanagar','Bahavanagar'),
    ('Ahmedabad','Ahmedabad'),
    ('Baroda','Baroda'),
    ('Mumbai','Mumbai'),
    ('Nasik','Nasik'),
    ('Pune','Pune'),
    ('Suratkal','Suratkal'),
    ('Manglor','Manglor'),
    ('Banglore','Banglore'),
 )
 COLLEGE_CHOICES=(
    ('NITK','NITK'),
    ('D Y Patil','D Y Patil'),
    ('SVNIT','SVNIT'),
 )
 name = models.CharField(max_length=200)
 state = models.CharField(max_length=200, choices=STATE_CHOICES)
 city = models.CharField(max_length=200, choices=CITY_CHOICES)
 college = models.CharField(max_length=200, choices=COLLEGE_CHOICES)
 age = models.IntegerField(default=0)
 def __str__(self):
        return self.name

class State(models.Model):
 name = models.CharField(max_length=200)
 def __str__(self):
        return self.name

class City(models.Model):
 state_name = models.ForeignKey(State, on_delete=models.CASCADE)
 name = models.CharField(max_length=200)
 def __str__(self):
        return self.name

class College(models.Model):
 name = models.CharField(max_length=200)
 def __str__(self):
        return self.name

webrecruitment/music/forms.py
from django import forms
from .models import Person, City, College, State


class PersonForm(forms.ModelForm):
  class Meta:
   model = Person
   fields = ['name', 'state', 'city', 'college', 'age']
  

webrecruitment/music/views.py
from django.shortcuts import render,redirect
from .models import Person,State,City,College
from .forms import PersonForm
from django.http import JsonResponse

def index(request):
 people = Person.objects.all()   
 contex = {'people': people }
 return render(request,'music/index.html',contex)

def detailes(request,person_id):
  a = Person.objects.all()
  contex = {'c': a,'b': person_id}
  return render(request,'music/detailes.html',contex)
 
def statistics(request):
 sum=0
 count=0
 count1=0
 a=[0]*len(State.objects.all())
 b=[0]*len(College.objects.all())
 c=[0]*len(City.objects.all())
 for person in Person.objects.all():
  sum=sum+person.age
  count=count+1
  count1=0
  for state in State.objects.all():
   if (state.name==person.state):
    a[count1]=a[count1]+1
    break 
   else:
    count1=count1+1
  count1=0
  for college in College.objects.all():
   if (college.name==person.college):
    b[count1]=b[count1]+1
   else:
    count1=count1+1
  count1=0
  for city in City.objects.all():
   if (city.name==person.city):
    c[count1]=c[count1]+1
   else:
    count1=count1+1 
 avarage=sum/count
 i=0
 d=['']*len(State.objects.all())
 e=['']*len(College.objects.all())
 f=['']*len(City.objects.all())
 for state in State.objects.all():
  a[i]=a[i]*100/count
  a[i]=round(a[i],2)
  d[i] = state.name + " : " + str(a[i])
  i=i+1
 i=0
 for college in College.objects.all():
  b[i]=b[i]*100/count
  b[i]=round(b[i],2)
  e[i] = college.name + " : " + str(b[i])
  i=i+1
 i=0
 for city in City.objects.all():
  c[i]=c[i]*100/count
  c[i]=round(c[i],2)
  f[i] = city.name + " : " + str(c[i])
  i=i+1
 r=0
 contex = { 's': d,'ci': f, 'co': e, 'avr': avarage, 'z': count}
 return render(request,'music/statistics.html',contex)
def new(request):
    if request.method == "POST":
        form = PersonForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.save()
            return redirect('/music') 
    else:
         form = PersonForm()
         return render(request, 'music/new.html', {'form': form})
def ajax(request):
 state_id=request.GET.get('state_id')
 states=State.objects.filter(name=state_id)
 for i in (states):
  cities=City.objects.filter(state_name=i.id)
 a=['']*len(cities)
 i=0
 for e in (cities):
  a[i]=e.name
  i=i+1  
 data = {'rooms': a}
 return JsonResponse(data)
    
  

webrecruitment/music/templates/music/detailes.html
{% for a in c %}
<ul>
{% if a.id == b  %}
<h1>{{ a.name }}</h1>
<li>{{ a.state }}</li>
<li>{{ a.city }}</li>
<li>{{ a.college }}</li>
<li>{{ a.age }}</li>
</ul>
{% endif %}
{% endfor %}
<h1><a href="/music/statistics/">Survey Results</a></h1>

webrecruitment/music/templates/music/index.html
<ul>
{% for person in people %}
<li><h1><a href="/music/{{ person.id }}/">{{ person.name }}</a></h1></li>
{% endfor %}
</ul>

webrecruitment/music/templates/music/new.html
 <h2>Person Form</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_p }}
    </table>
    <button type="submit">Save</button>
  </form>
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js">
</script>
<script>
$(document).ready(function(){
  $("#id_state").change(function(){ var state_id = $(this).val();
    $.ajax({
            url: '/music/ajax/',
            type: 'GET',
            dataType: 'json',
            data: {state_id: state_id},
             error: function (xhr, status, error) {
    },
    success: function (response) { var ID="#id_city";
      var rooms = response["rooms"];
      $(ID).empty();
      var q=rooms.length;
      console.log(q);
      $(ID).append('<option>Select city</option>');
      for(var i=0; i< rooms.length; i++){ 
        $(ID).append($('<option>', {
                    value: rooms[i],
                    text: rooms[i]
                }));

      }
    }
  });
  });
});
</script>

webrecruitment/music/templates/music/statistics.html
<h1>Results of the survey</h1>
<h3>Number of people in the survey : {{ z }}</h3>
<h2>States</h2>
{% for i in s %}
{{ i }}%<br>
{% endfor %}
<h2>Cities</h2>
{% for i in ci %}
{{ i }}%<br>
{% endfor %}
<h2>Colleges</h2>
{% for i in co %}
{{ i }}%<br>
{% endfor %}